# intro



```{r setup01, include=FALSE}
require(tableone)
require(Publish)
require(MatchIt)
require(cobalt)
```


```{r}
knitr::include_url('https://ehsanx.github.io/hdps-slides/#13')
```


```{block, type='rmdcomment'}
Data is freely available from [Vanderbilt Biostatistics](https://hbiostat.org/data/).
```

# Data

```{r}
library("autoCovariateSelection")
library("dplyr")
data(rwd)
head(rwd)
CreateTableOne(data = rwd, vars = c("domain", "treatment"))
```

# Base table

```{r}
basetable <- rwd %>% select(person_id, treatment, outcome_date) %>% distinct()
basetable[complete.cases(basetable),]
```

# ID

```{r}
patientIds <- basetable$person_id #this can be used as patientIdVector argument for the functions in this package
length(unique(patientIds))
```

# Step 1

```{r}
step1 <- get_candidate_covariates(df = rwd,  domainVarname = "domain", eventCodeVarname = "event_code" ,
                                  patientIdVarname = "person_id", patientIdVector = patientIds,n = 1000, min_num_patients = 10)
names(step1)
step1$covars[step1$covars$prevalence > 10,]
step1$covars_data[step1$covars_data$person_id=="21047",]
```

# Step 1 output

```{r}
out1 <- step1$covars_data #this will be input to get_recurrence_covariates() function
out1
```

# Step 2

```{r}
step2 <- get_recurrence_covariates(df = out1, patientIdVarname = "person_id", eventCodeVarname = "event_code", patientIdVector = patientIds)
names(step2)
dim(step2$recurrence_data)
```

# Step 2 output

```{r}
out2 <- step2$recurrence_data #this will be input to get_prioritised_covariates() function
out2
head(out2)
```

# Step 3

```{r}
step3 <- get_prioritised_covariates(df = out2, patientIdVarname = "person_id", exposureVector = basetable$treatment,
                                    outcomeVector = ifelse(is.na(basetable$outcome_date), 0,1),patientIdVector = patientIds, k = 10)
head(step3$autoselected_covariate_df)
dim(step3$autoselected_covariate_df)
```

# Step 3 output

```{r}
out3 <- step3$autoselected_covariate_df #dataframe containing the auto selected covariates for all the subjects in the table  
out3
```

